apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: git-registry.gibb.ch/mda133769/xserver/xserver-frontend:v0.1.9-prod
        ports:
        - containerPort: 80
