{
 "title": "Payment Service Metrics",
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Requests by Method",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_requests_total[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests by Route",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum by (route) (rate(http_requests_total[1m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Requests by Status",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "Status {{status}}"
    }
   ]
  },
  {
   "title": "Total Processed Messages",
   "type": "stat",
   "gridPos": { "x": 0, "y": 12, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "sum(payment_created_messages_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Payment Processed Messages by Status",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 12, "w": 18, "h": 6 },
   "targets": [
    {
     "expr": "rate(payment_created_messages_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}