apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gameserver
  name: deployment-manager
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "replicasets", "services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: gameserver
subjects:
- kind: ServiceAccount
  name: custom-sa
  namespace: default
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
