global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:3003']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']