stages:
  - frontend-build-image
  - frontend-build-image-release

frontend-build-image:
  stage: frontend-build-image
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  variables:
    IMAGE_TAG: "${CI_REGISTRY}/mda133769/xserver/xserver-frontend:$CI_COMMIT_REF_SLUG"
  script:
    - IMAGE_TAG="${CI_REGISTRY}/mda133769/xserver/xserver-frontend:latest"
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context ./frontend
      --dockerfile Dockerfile
      --destination $IMAGE_TAG

frontend-build-image-release:
    stage: frontend-build-image-release
    image:
        name: gcr.io/kaniko-project/executor:v1.14.0-debug
        entrypoint: [""]
    rules:
        - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /prod/'
    variables:
        IMAGE_TAG: "${CI_REGISTRY}/mda133769/xserver/xserver-frontend:${CI_COMMIT_TAG}"
    script:
        - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64)\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor
            --context ./frontend
            --dockerfile Dockerfile
            --destination $IMAGE_TAG

frontend-build-image-release-prod:
    stage: frontend-build-image-release
    image:
        name: gcr.io/kaniko-project/executor:v1.14.0-debug
        entrypoint: [""]
    rules:
        - if: '$CI_COMMIT_TAG =~ /prod/'
    variables:
        IMAGE_TAG: "${CI_REGISTRY}/mda133769/xserver/xserver-frontend:${CI_COMMIT_TAG}"
    script:
        - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64)\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor --context ./frontend --dockerfile Dockerfile-Prod --destination $IMAGE_TAG
